---
###############################################################################
# COMMON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 
      - 'npm-pipeline.yml'
    ref: 'v1.4.2'
    
variables:
  CUSTOMER: 'coghent'
  APPLICATION: 'coghent-box-frontend'
  TERRAFORM_IMAGE: 'box-terraform'
  TERRAFORM_TAG: 'latest'
  SKIP_DEPLOY: 'true'
