---
###############################################################################
# NPM APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'npm-pipeline.yml'
    ref: 'v1.4.2'
  - project: 'customers/coghent/infra/coghent-infra-gitlab-templates'
    file    : 'box-to-coghent.yml'
    ref     : 'master'


variables:
  CUSTOMER: 'coghent'
  APPLICATION: 'coghent-box-frontend'
  SKIP_DEPLOY: 'true'
